### ISSUE TITLE
Warning on compilation - production build fails

### ISSUE THREAD

**Issue by 0xTimepunk** [3box/3id-connect#86] opened 2020-11-22 20:01 UTC
HI, I get this error 

![image](https://user-images.githubusercontent.com/45543880/99915735-589d8b80-2cfd-11eb-9148-19a79671f0a1.png)

Using     "3id-connect": "1.0.0-alpha.3"

How can it be solved so I can create a production build?

Error in Netlify 

![image](https://user-images.githubusercontent.com/45543880/99915751-74089680-2cfd-11eb-88b6-6b3dab1417ac.png)

Thanks

**Comment by ukstv** [comment] 2020-11-23 15:04
Hey, @j-mars mind posting here a command you use to summon these warnings/errors?

**Comment by 0xTimepunk** [comment] 2020-11-24 16:01
> Hey, @j-mars mind posting here a command you use to summon these warnings/errors?

Hi,

I created a test repo with basic Create-React-App with latest React 17 so you can just do yarn and yarn start to check the issue

https://github.com/j-mars/3id-connect-test

The warning appears after building in dev mode and then if you want to go to production mode, yarn build fails.


Let me know if I should add extra details to this setup.

**Comment by ukstv** [comment] 2020-11-24 16:16
Thanks @j-mars this feels enough for me to figure a proper mitigation.

**Comment by 0xTimepunk** [comment] 2020-11-24 16:43
> Thanks @j-mars this feels enough for me to figure a proper mitigation.

Thanks for your help

I added a setup with redux and redux-saga to simulate a connection to Ethereum / Ceramic / Skynet.

If there's an error when building because of jest just add a Skip Preflight Check to a .env file

**Comment by ukstv** [comment] 2020-11-25 14:17
@j-mars Warning is (almost) ok. To unblock you, please, set CI variable to something not true. https://community.netlify.com/t/new-ci-true-build-configuration-treating-warnings-as-errors-because-process-env-ci-true/14434 Default value `CI=true` turns warnings into errors.

**Comment by 0xTimepunk** [comment] 2020-11-25 15:14
> @j-mars Warning is (almost) ok. To unblock you, please, set CI variable to something not true. https://community.netlify.com/t/new-ci-true-build-configuration-treating-warnings-as-errors-because-process-env-ci-true/14434 Default value `CI=true` turns warnings into errors.

Hi @ukstv  thank you, I will apply that remedy for now!

**Comment by ukstv** [comment] 2021-02-01 16:44
Hey, @j-mars while the issue is effectively resolved by disabling Filecoin linking, there is work to do (https://github.com/ceramicstudio/3id-connect/issues/19) to re-enable this in upstream 3id-connect.

So, I am closing this issue with an invitation to follow https://github.com/ceramicstudio/3id-connect/issues/19 if you wish.

**Closed as completed by ukstv** 2021-02-01 16:44 UTC
Labels: bug
